/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as ActiveCallsRouteImport } from './routes/active-calls'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MachinesMachineIdRouteImport } from './routes/machines.$machineId'
import { Route as MachinesMachineIdCallHistoryRouteImport } from './routes/machines.$machineId.call-history'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ActiveCallsRoute = ActiveCallsRouteImport.update({
  id: '/active-calls',
  path: '/active-calls',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineIdRoute = MachinesMachineIdRouteImport.update({
  id: '/machines/$machineId',
  path: '/machines/$machineId',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineIdCallHistoryRoute =
  MachinesMachineIdCallHistoryRouteImport.update({
    id: '/call-history',
    path: '/call-history',
    getParentRoute: () => MachinesMachineIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/active-calls': typeof ActiveCallsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/machines/$machineId': typeof MachinesMachineIdRouteWithChildren
  '/machines/$machineId/call-history': typeof MachinesMachineIdCallHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/active-calls': typeof ActiveCallsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/machines/$machineId': typeof MachinesMachineIdRouteWithChildren
  '/machines/$machineId/call-history': typeof MachinesMachineIdCallHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/active-calls': typeof ActiveCallsRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/machines/$machineId': typeof MachinesMachineIdRouteWithChildren
  '/machines/$machineId/call-history': typeof MachinesMachineIdCallHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/active-calls'
    | '/history'
    | '/settings'
    | '/machines/$machineId'
    | '/machines/$machineId/call-history'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/active-calls'
    | '/history'
    | '/settings'
    | '/machines/$machineId'
    | '/machines/$machineId/call-history'
  id:
    | '__root__'
    | '/'
    | '/active-calls'
    | '/history'
    | '/settings'
    | '/machines/$machineId'
    | '/machines/$machineId/call-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActiveCallsRoute: typeof ActiveCallsRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  MachinesMachineIdRoute: typeof MachinesMachineIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/active-calls': {
      id: '/active-calls'
      path: '/active-calls'
      fullPath: '/active-calls'
      preLoaderRoute: typeof ActiveCallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machineId': {
      id: '/machines/$machineId'
      path: '/machines/$machineId'
      fullPath: '/machines/$machineId'
      preLoaderRoute: typeof MachinesMachineIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machineId/call-history': {
      id: '/machines/$machineId/call-history'
      path: '/call-history'
      fullPath: '/machines/$machineId/call-history'
      preLoaderRoute: typeof MachinesMachineIdCallHistoryRouteImport
      parentRoute: typeof MachinesMachineIdRoute
    }
  }
}

interface MachinesMachineIdRouteChildren {
  MachinesMachineIdCallHistoryRoute: typeof MachinesMachineIdCallHistoryRoute
}

const MachinesMachineIdRouteChildren: MachinesMachineIdRouteChildren = {
  MachinesMachineIdCallHistoryRoute: MachinesMachineIdCallHistoryRoute,
}

const MachinesMachineIdRouteWithChildren =
  MachinesMachineIdRoute._addFileChildren(MachinesMachineIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActiveCallsRoute: ActiveCallsRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  MachinesMachineIdRoute: MachinesMachineIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
