import { useEffect, useMemo, useState } from "react";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { CALL_TYPE_OPTIONS } from "@/data/callTypes";
import { useAndon } from "@/context/AndonProvider";
import { DEFAULT_SOUND_MACHINE_ID, type SoundMachineId } from "@/types/sound";
import { getSoundConfig, listSoundConfigs, removeSoundConfig, saveSoundConfig } from "@/services/soundStorageService";
import { testAndonSound } from "@/services/soundService";
import { BigButton } from "@/components/common/BigButton";
import { toast } from "sonner";
import type { AndonCategoryConfig, SettingsTab, ShiftConfig, TechnicianConfig } from "@/types/settings";
import { getTechnicianConfigs, saveTechnicianConfigs } from "@/services/technicianConfigService";
import { DEFAULT_SHIFTS, getShiftConfigs, saveShiftConfigs } from "@/services/shiftConfigService";
import { DEFAULT_CATEGORIES, getCategoryConfigs, saveCategoryConfigs } from "@/services/categoryConfigService";
import { logoutAdmin } from "@/services/adminAuthService";

export function AdminSettingsModal({ open, onOpenChange }: { open: boolean; onOpenChange: (open: boolean) => void }) {
  const [tab, setTab] = useState<SettingsTab>("sounds");
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] max-w-5xl overflow-y-auto"><DialogHeader><DialogTitle>Configurações do Sistema</DialogTitle><DialogDescription>Painel administrativo do ANDON.</DialogDescription></DialogHeader><div className="flex gap-2 flex-wrap">{[["sounds","Sons do ANDON"],["technicians","Manutentores"],["categories","Categorias"],["shifts","Turnos"]].map(([id,label])=><button key={id} className={`rounded-md border px-4 py-2 ${tab===id?"bg-primary text-primary-foreground":"bg-card"}`} onClick={()=>setTab(id as SettingsTab)}>{label}</button>)}</div>{tab==="sounds"&&<SoundsTab/>}{tab==="technicians"&&<TechniciansTab/>}{tab==="categories"&&<CategoriesTab/>}{tab==="shifts"&&<ShiftsTab/>}<div className="flex justify-between"><BigButton tone="danger" size="md" onClick={()=>{logoutAdmin();onOpenChange(false);}}>Sair do modo admin</BigButton><BigButton tone="neutral" size="md" onClick={()=>onOpenChange(false)}>Fechar</BigButton></div></DialogContent></Dialog>;
}

function SoundsTab(){ const {machines}=useAndon(); const [machineId,setMachineId]=useState<SoundMachineId>(DEFAULT_SOUND_MACHINE_ID); const [subtype,setSubtype]=useState(CALL_TYPE_OPTIONS[0].id); const [selectedFile,setSelectedFile]=useState<File|null>(null); const [configs,setConfigs]=useState<any[]>([]); const [currentConfig,setCurrentConfig]=useState<any|null>(null); const acceptedTypes=useMemo(()=>["audio/mpeg","audio/wav","audio/ogg"],[]); async function refresh(){const [list,config]=await Promise.all([listSoundConfigs(),getSoundConfig(machineId,subtype)]);setConfigs(list);setCurrentConfig(config);} useEffect(()=>{void refresh();},[machineId,subtype]); async function save(){if(!selectedFile)return toast.error("Nenhum som configurado para esta seleção."); if(!acceptedTypes.includes(selectedFile.type)&&!/\.(mp3|wav|ogg)$/i.test(selectedFile.name))return toast.error("Formato inválido. Use .mp3, .wav ou .ogg."); await saveSoundConfig(machineId,subtype,selectedFile); setSelectedFile(null); await refresh(); toast.success("Som salvo com sucesso.");}
return <div className="space-y-3"><div className="grid gap-3 md:grid-cols-2"><label>Máquina<select className="mt-1 w-full rounded-md border bg-slate-950 p-2" value={machineId} onChange={(e)=>setMachineId(e.target.value)}><option value="default">Padrão para todas</option>{machines.map((m)=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label>Tipo de chamado<select className="mt-1 w-full rounded-md border bg-slate-950 p-2" value={subtype} onChange={(e)=>setSubtype(e.target.value as any)}>{CALL_TYPE_OPTIONS.map((o)=><option key={o.id} value={o.id}>{o.label}</option>)}</select></label></div><input type="file" accept=".mp3,.wav,.ogg,audio/mpeg,audio/wav,audio/ogg" onChange={(e)=>setSelectedFile(e.target.files?.[0]??null)}/>{selectedFile&&<p className="text-xs">{selectedFile.name}</p>}{currentConfig&&<p className="text-xs">Atual: {currentConfig.fileName}</p>}<div className="flex gap-2 flex-wrap"><BigButton tone="info" size="md" onClick={()=>void testAndonSound(machineId,subtype)}>Testar som</BigButton><BigButton tone="danger" size="md" onClick={()=>void removeSoundConfig(machineId,subtype).then(refresh)}>Remover som</BigButton><BigButton tone="primary" size="md" onClick={()=>void save()}>Salvar</BigButton></div><div><div className="font-bold">Sons configurados</div>{configs.map((cfg)=><button key={cfg.id} className="block text-left text-xs hover:underline" onClick={()=>{setMachineId(cfg.machineId);setSubtype(cfg.subtype);setSelectedFile(null);}}> {cfg.machineId==="default"?"Padrão":`Máquina ${cfg.machineId}`} · {CALL_TYPE_OPTIONS.find((o)=>o.id===cfg.subtype)?.label ?? cfg.subtype} · {cfg.fileName}</button>)}</div></div> }

function TechniciansTab(){const [items,setItems]=useState<TechnicianConfig[]>([]); const [draft,setDraft]=useState<TechnicianConfig>({id:"",name:"",area:"electrical",shifts:[],active:true}); useEffect(()=>setItems(getTechnicianConfigs()),[]); function save(){const id=draft.id||`tech-${Date.now()}`; const next=[...items.filter((i)=>i.id!==id),{...draft,id}]; setItems(next); saveTechnicianConfigs(next);} return <div className="space-y-2"><input className="w-full rounded border p-2" placeholder="Nome do manutentor" value={draft.name} onChange={(e)=>setDraft({...draft,name:e.target.value})}/><select className="w-full rounded border p-2" value={draft.area} onChange={(e)=>setDraft({...draft,area:e.target.value as any})}><option value="electrical">Elétrica</option><option value="mechanical">Mecânica</option><option value="hot_melt">Hot Melt</option><option value="quality">Qualidade</option><option value="leadership">Liderança</option></select><div className="grid grid-cols-2 gap-2">{DEFAULT_SHIFTS.map((s)=><label key={s.id}><input type="checkbox" checked={draft.shifts.includes(s.id)} onChange={()=>setDraft({...draft,shifts:draft.shifts.includes(s.id)?draft.shifts.filter((x)=>x!==s.id):[...draft.shifts,s.id]})}/> {s.name}</label>)}</div><label><input type="checkbox" checked={draft.active} onChange={(e)=>setDraft({...draft,active:e.target.checked})}/> Ativo</label><BigButton tone="primary" size="md" onClick={save}>Salvar manutentor</BigButton><div className="space-y-1">{items.map((t)=><button key={t.id} className="block w-full rounded border p-2 text-left" onClick={()=>setDraft(t)}>{t.name} · {t.active?"Ativo":"Inativo"}</button>)}</div></div>}

function CategoriesTab(){const [items,setItems]=useState<AndonCategoryConfig[]>([]); useEffect(()=>setItems(getCategoryConfigs()),[]); function persist(next:AndonCategoryConfig[]){setItems(next);saveCategoryConfigs(next);} return <div className="space-y-2">{items.map((c)=><div key={c.id} className="flex items-center gap-2"><input className="rounded border p-1" value={c.displayName} onChange={(e)=>persist(items.map((x)=>x.id===c.id?{...x,displayName:e.target.value}:x))}/><label><input type="checkbox" checked={c.active} onChange={(e)=>persist(items.map((x)=>x.id===c.id?{...x,active:e.target.checked}:x))}/> Ativo</label><span className="text-xs text-muted-foreground">({c.id})</span></div>)}</div>}

function ShiftsTab(){const [items,setItems]=useState<ShiftConfig[]>([]); useEffect(()=>setItems(getShiftConfigs()),[]); function persist(next:ShiftConfig[]){setItems(next);saveShiftConfigs(next);} return <div className="space-y-2">{items.map((s)=><div key={s.id} className="grid grid-cols-1 gap-2 rounded border p-2 md:grid-cols-5"><div>{s.name}</div><input type="time" value={s.startTime} onChange={(e)=>persist(items.map((x)=>x.id===s.id?{...x,startTime:e.target.value,crossesMidnight:e.target.value>x.endTime}:x))}/><input type="time" value={s.endTime} onChange={(e)=>persist(items.map((x)=>x.id===s.id?{...x,endTime:e.target.value,crossesMidnight:x.startTime>e.target.value}:x))}/><label><input type="checkbox" checked={s.active} onChange={(e)=>persist(items.map((x)=>x.id===s.id?{...x,active:e.target.checked}:x))}/> Ativo</label><div className="text-xs">{s.crossesMidnight?"Cruza meia-noite":"Mesmo dia"}</div></div>)}</div>}
